(define (problem asfaltado)
(:domain asfaltado)
(:objects
    tramo1 - tramo
    tramo2 - tramo
    tramo3 - tramo
    tramo4 - tramo
    tramo5 - tramo
    cuadrilla1 - cuadrilla
    cuadrilla2 - cuadrilla
    cuadrilla3 - cuadrilla
    cuadrilla4 - cuadrilla
    cisterna_asfalto1 - cisterna
    cisterna_asfalto2 - cisterna
    pavimentadora1 - pavimentadora
    pavimentadora2 - pavimentadora
    compactadora1 - compactadora
)

(:init
	(at tramo1 cuadrilla1)
	(at tramo1 cuadrilla2)
    (at tramo5 cuadrilla3)
    (at tramo5 cuadrilla4)
    (at tramo1 cisterna_asfalto1)
    (at tramo1 cisterna_asfalto2)
    (at tramo2 pavimentadora1)
    (at tramo2 pavimentadora2)
    (at tramo5 compactadora1)
    (conectado tramo1 tramo1)
    (conectado tramo1 tramo2)
    (conectado tramo2 tramo1)
    (conectado tramo2 tramo2)
    (conectado tramo2 tramo3)
    (conectado tramo2 tramo4)
    (conectado tramo3 tramo2)
    (conectado tramo3 tramo3)
    (conectado tramo3 tramo5)
    (conectado tramo4 tramo2)
    (conectado tramo4 tramo4)
    (conectado tramo4 tramo5)
    (conectado tramo5 tramo3)
    (conectado tramo5 tramo4)
    (conectado tramo5 tramo5)
    (= (distance tramo1 tramo1) 0)
    (= (distance tramo1 tramo2) 5)
    (= (distance tramo2 tramo1) 5)
    (= (distance tramo2 tramo2) 0)
    (= (distance tramo2 tramo3) 6)
    (= (distance tramo2 tramo4) 4)
    (= (distance tramo3 tramo2) 6)
    (= (distance tramo3 tramo3) 0)
    (= (distance tramo3 tramo5) 7)
    (= (distance tramo4 tramo2) 4)
    (= (distance tramo4 tramo4) 0)
    (= (distance tramo4 tramo5) 6)
    (= (distance tramo5 tramo3) 7)
    (= (distance tramo5 tramo4) 6)
    (= (distance tramo5 tramo5) 0)
	
	
	(= (distance tramo1 tramo3) 0)
	(= (distance tramo1 tramo4) 0)
	(= (distance tramo1 tramo5) 0)
	(= (distance tramo2 tramo5) 0)
	(= (distance tramo3 tramo1) 0)
	(= (distance tramo3 tramo4) 0)
	(= (distance tramo4 tramo3) 0)
	(= (distance tramo4 tramo1) 0)
	(= (distance tramo5 tramo1) 0)
	(= (distance tramo5 tramo2) 0)
	
	
    (compactado tramo3)
    (compactado tramo4)
    (compactado tramo5)
    (need_sign tramo3)
    (need_sign tramo4)
	(need_sign tramo5)
	(sign tramo1)
	(sign tramo2)
    (disponible tramo1)
    (disponible tramo2)
    (disponible tramo3)
    (disponible tramo4)
    (disponible tramo5)
    (disponible cuadrilla1)
    (disponible cuadrilla2)
    (disponible cuadrilla3)
    (disponible cuadrilla4)
    (disponible cisterna_asfalto1)
    (disponible cisterna_asfalto2)
    (disponible pavimentadora1)
    (disponible pavimentadora2)
    (disponible compactadora1)
    (= (coste cisterna_asfalto1) 25)
    (= (coste cisterna_asfalto2) 25)
    (= (coste pavimentadora1) 30)
    (= (coste pavimentadora2) 30)
    (= (coste compactadora1) 35)
    (= (coste-total) 0)
)

(:goal (and
	(at tramo1 cuadrilla1)
	(at tramo5 cuadrilla2)
    (at tramo5 cuadrilla4)
    (at tramo1 cisterna_asfalto1)
    (at tramo3 cisterna_asfalto2)
    (at tramo5 compactadora1)
	(aplastado tramo1)
	(aplastado tramo2)
	(aplastado tramo3)
	(aplastado tramo4)
	(aplastado tramo5)
	(sign tramo1)
	(sign tramo2)
	(sign tramo3)
	(sign tramo4)
	(sign tramo5)
	(pintado tramo1)
	(pintado tramo2)
	(pintado tramo3)
	(pintado tramo4)
	(pintado tramo5)
	(vallas tramo1)
	(vallas tramo2)
	(vallas tramo3)
	(vallas tramo4)
	(vallas tramo5)
    )
)

(:metric minimize (+ (*0.2 (total-time)) (*0.5 (coste-total))))

)
